package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.65

import (
	"context"
	"errors"
	"strconv"
	"time"
	"user-management-service/internal/models"
	"user-management-service/internal/repository"
)

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, name string, email string) (*models.User, error) {
	defer r.TrackExecutionTime(time.Now(), "CreateUser")
	user := &models.User{
		Name:  name,
		Email: email,
	}
	if err := repository.CreateUser(user); err != nil {
		return nil, err
	}
	return user, nil
}

// DeleteUser is the resolver for the deleteUser field.
func (r *mutationResolver) DeleteUser(ctx context.Context, id string) (bool, error) {
	defer r.TrackExecutionTime(time.Now(), "DeleteUser")
	idInt, err := strconv.Atoi(id)
	if err != nil {
		return false, errors.New("invalid user ID format")
	}

	if err := repository.DeleteUser(idInt); err != nil {
		return false, err
	}
	return true, nil
}

// UpdateUser is the resolver for the updateUser field.
func (r *mutationResolver) UpdateUser(ctx context.Context, id string, name string, email string) (*models.User, error) {
	defer r.TrackExecutionTime(time.Now(), "UpdateUser")
	idInt, err := strconv.Atoi(id)
	if err != nil {
		return nil, errors.New("invalid user ID format")
	}

	user := &models.User{
		ID:    idInt,
		Name:  name,
		Email: email,
	}

	if err := repository.UpdateUser(user); err != nil {
		return nil, err
	}
	return user, nil
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context) ([]*models.User, error) {
	defer r.TrackExecutionTime(time.Now(), "Users")
	return repository.GetAllUsers()
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, id string) (*models.User, error) {
	defer r.TrackExecutionTime(time.Now(), "User")
	idInt, err := strconv.Atoi(id)
	if err != nil {
		return nil, errors.New("invalid user ID format")
	}
	return repository.GetUserByID(idInt)
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
