// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"user-management-service/internal/models"
)

type AuthResponse struct {
	Token string       `json:"token"`
	User  *models.User `json:"user"`
}

type Mutation struct {
}

type Query struct {
}
